version: '3.8'
services:
  fastapi:
    build: .
    depends_on:
      - postgres
    restart: always
    volumes:
      - "./app:/app/"
      - "./app/images:/images"
    ports:
        - "8000:8000"
    networks:
      - net


  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/www/data/static
      - ./app/images:/www/data/images
    networks:
      - net
    depends_on:
      - fastapi

  postgres:
    image: "postgres"
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "tweet_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    networks:
      - net
    ports:
      - "5432:5432"

networks:
  net:
    driver: bridge
