version: '3.8'
services:
  fastapi:
    build: .
    depends_on:
      - postgres
    restart: always
    volumes:
      - "./app/:/app/"
    networks:
      - db_network
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/www/data/static
      - ./app/images:/www/data/images
    networks:
      - web_network
    depends_on:
      - fastapi

  postgres:
    image: "postgres"
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "tweet_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    networks:
      - db_network
    ports:
      - "5432:5432"

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
