[tool.poetry]
name = "python-advanced-diploma"
version = "0.1.0"
description = "Clone-tweets"
authors = ["ramazan_aisaev <aisaev-68@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
asyncpg = "^0.27.0"
anyio = "^3.6.2"
fastapi = "^0.88.0"
sqlalchemy = "^1.4.45"
greenlet = "^2.0.1"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
aiofiles = "^22.1.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.5"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pytest-asyncio = "^0.20.3"
httpx = "^0.23.1"
jinja2 = "^3.1.2"
mypy = "^0.991"
pytest = "^7.2.0"
isort = "^5.11.2"
flake8 = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
