[tool.poetry]
name = "python-advanced-diploma"
version = "0.1.0"
description = "Clone-tweets"
authors = ["ramazan_aisaev <aisaev-68@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
asyncpg = "^0.27.0"
anyio = "^3.6.2"
fastapi = "^0.88.0"
greenlet = "^2.0.1"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
aiofiles = "^22.1.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.5"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pytest-asyncio = "^0.20.3"
httpx = "^0.23.1"
jinja2 = "^3.1.2"
alembic = "^1.9.0"
setuptools = "^65.6.3"
pydantic = "^1.10.2"
sqlacodegen = {extras = ["citext"], version = "^2.3.0"}
sqlalchemy = "1.4.35"
sqlmodel = "^0.0.8"
wemake-python-styleguide = "^0.17.0"
trio = "^0.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
