FROM python:3.10
RUN mkdir /app
WORKDIR /app
ADD requirements.txt /app
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

ADD . /app
EXPOSE 8000
ENTRYPOINT ["uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
