version: "3"
services:
  app:
    build:
      context: app
    restart: always
    stop_signal: SIGKILL
    ports:
      - "8000:8000"
    links:
      - postgres
    volumes:
      - ./app/:/app/
#    depends_on:
#      - postgres
    networks:
      - net


  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "tweet_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - net

networks:
  net:
    driver: bridge